//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public product_category()
        {
            this.client_user = new HashSet<client_user>();
            this.product = new HashSet<product>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<client_user> client_user { get; set; }
        public virtual ICollection<product> product { get; set; }
    }
}
