//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.article = new HashSet<article>();
        }
    
        public int Id { get; set; }
        public byte Category_Id { get; set; }
        public string Blocking_User_Id { get; set; }
    
        public virtual ICollection<article> article { get; set; }
        public virtual client_user client_user { get; set; }
        public virtual product_category product_category { get; set; }
    }
}
