//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class virtualpoolEntities : DbContext
    {
        public virtualpoolEntities()
            : base("name=virtualpoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<article> article { get; set; }
        public DbSet<client_user> client_user { get; set; }
        public DbSet<pool> pool { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<product_category> product_category { get; set; }
    }
}
